#ifndef __SOCKET_DEMO_DEFINE_H__
#define __SOCKET_DEMO_DEFINE_H__

enum Marker
{
    MESSAGE_BOOLEAN = 0x01,
    MESSAGE_STRING = 0x02,
    MESSAGE_NUM = 0X00,
    MESSAGE_OBJECT = 0x03,
    MESSAGE_END_OF_OBJECT = 0x09,
    MESSAFE_NULL_OBJECT = 0x05,
    MESSAFE_UNDEFINED = 0x06
};

enum MESSAGE_OBJECT_TYPE
{
    CONNECT_APP_RESPONSE = 0,
    ON_BW_DONE = 1,
    PULL_ONSTATUS1 = 2,
    PULL_ONSTATUS2 = 3,
    PULL_ONSTATUS3 = 4
};

#endif